### ISSUE TITLE
Render-функции→ Аргументы createElement → пример

### ISSUE THREAD

**Issue by Leadaxe** [translation-gang/ru.vuejs.org#153]
https://ru.vuejs.org/v2/guide/render-function.html#Аргументы-createElement
``` javascript
// @returns {VNode}
createElement(
  // {String | Object | Function}
  // Название тега HTML, опции компонента, или функция,
  // их возвращающая. Обязательный параметр.
  'div',
```

**опции компонента** — это, видимо, название (name) компонента?

**Comment by gbezyuk** [comment]
ping @Alex-Sokolov

**Comment by gbezyuk** [comment]
@Leadaxe см. https://vuejs.org/v2/guide/render-function.html#createElement-Arguments. Опции компонента — это опции компонента. Имя — String, опции — Object.
