### ISSUE TITLE
Пропущено слово в api/#watch

### ISSUE THREAD

**Issue by Seigiard** [translation-gang/ru.vuejs.org#175]
Пропущено слово  в api/#watch

> Объект, ключи которого — выражения для наблюдения, а значения — коллбэки, вызываемые при их изменении. Значения также могут **быть? являться?** строками с именами методов, или объектами, содержащими дополнительные опции. Экземпляр Vue вызовет $watch() соответствующий каждому ключу объекта при своём создании.

Ожидается слово «быть» или «являться».

https://ru.vuejs.org/v2/api/#watch
https://github.com/translation-gang/ru.vuejs.org/blob/master/src/v2/api/index.md#watch

**Comment by gbezyuk** [comment]
PR is more than welcome ) @Alex-Sokolov, ты вернулся из отпуска уже?

**Comment by Alex-Sokolov** [comment]
@gbezyuk Вернулся) слово добавил (https://github.com/translation-gang/ru.vuejs.org/pull/174), сегодня попробую и накопившееся докидать туда же
