### ISSUE TITLE
Перезаписывается margin

### ISSUE THREAD

**Issue by ydakuka** [translation-gang/ru.vuejs.org#235]
И в переводной версии, и в оригинальное такое на странице:
https://ru.vuejs.org/v2/examples/hackernews.html может быть и на других тоже.

![https://image.ibb.co/gu7Zpb/2017_12_02_23_33_12.png](https://image.ibb.co/gu7Zpb/2017_12_02_23_33_12.png)

![https://image.ibb.co/jtcs9b/2017_12_02_23_36_02.png](https://image.ibb.co/jtcs9b/2017_12_02_23_36_02.png)

**Comment by Alex-Sokolov** [comment]
@ydakuka в таком случае стоит вносить правки в оригинальный репо сначала

**Comment by Alex-Sokolov** [comment]
https://github.com/vuejs/vuejs.org/issues/1308
