### ISSUE TITLE
Не корректый id якоря

### ISSUE THREAD

**Issue by victor-AA** [translation-gang/ru.vuejs.org#246]
https://ru.vuejs.org/v2/api/
Не работает переход при клике на **Методы экземпляра — жизненный цикл > vm.$mount**
Там указан  **#vm-mount-elementOrSelector** вместо **#vm-mount**
Та же проблема и в **vm.$nextTick**

**Comment by Alex-Sokolov** [comment]
Спасибо! Вот уже есть PR. Я проверил ссылки в API с ним отрабатывают корректно, так что переопубликовано уже с ним.

Ref: https://github.com/vuejs/vuejs.org/pull/1348
