### ISSUE TITLE
Вместо жирного шрифта использовался другой стиль подчёркивания ключевых слов

### ISSUE THREAD

**Issue by DmitriiMers** [translation-gang/ru.vuejs.org#247]
Render-функции и JSX, Основы: **render function** (оригинал) - **`render`-функции** (перевод)
[commit](https://github.com/translation-gang/ru.vuejs.org/commit/6e0d1c2b5c969df9c53f510fa0b38df39924500a#diff-ace1797ab50ff7853f4e2848d698e3d0)

**Comment by Alex-Sokolov** [comment]
Ну так там не жирным выделяется, а именно как вставками кода

**Comment by DmitriiMers** [comment]
Ну я имел в виду что шрифт на английской версии сайта отличается от Русской

**Comment by Alex-Sokolov** [comment]
Да, отличается. Потому что русские символы в том шрифты смотрятся плохо

**Comment by DmitriiMers** [comment]
Ясно,  спасибо. 
Значит это не issue
