### ISSUE TITLE
Не использовались подчеркнутые ключевые слова в Render-функции и JSX, Основы

### ISSUE THREAD

**Issue by DmitriiMers** [translation-gang/ru.vuejs.org#248]
перевод:
При использовании шаблонов для реализации такого интерфейса придётся написать что-то вроде кода ниже:

новый перевод
При использовании шаблонов для реализации интерфейса который генерирует только заголовок, основанный на свойстве `level`, вы быстро столкнетесь со следующей ситуацией:

[PR](https://github.com/translation-gang/ru.vuejs.org/pull/249)

**Comment by Alex-Sokolov** [comment]
Исправлено
