### ISSUE TITLE
Перевод изображений

### ISSUE THREAD

**Issue by greenroach** [translation-gang/ru.vuejs.org#279]
Нужен текстовый перевод следующих изображений:
- [x] data.png
![data](https://user-images.githubusercontent.com/6224866/36143918-875a6ed4-10bd-11e8-85c0-ff6ad29afdc6.png)
- [x] _dom-tree.png (перевод не требуется)_
![dom-tree](https://user-images.githubusercontent.com/6224866/36143945-9d26c244-10bd-11e8-889c-e49cba04f41b.png)
- [x] hn-architecture.png
![hn-architecture](https://user-images.githubusercontent.com/6224866/36143950-9f81e028-10bd-11e8-8ec7-b6dd233cecce.png)
- [x] mvvm.png
![mvvm](https://user-images.githubusercontent.com/6224866/36143962-a7b37784-10bd-11e8-96b5-3c3fd74354ef.png)

- [x] _transition.png (перевод не требуется)_

![transition](https://user-images.githubusercontent.com/6224866/36143966-a950aa94-10bd-11e8-874b-f6457a56715c.png)

**Comment by Alex-Sokolov** [comment]
data.png
- Рендер-функция компонента
- Дерево виртуального DOM
- render
- "затрагивает"
- data getter/setter наверное так и лучше оставить
- запоминает как зависимость
- уведомляет
- watcher наверное тоже так и оставить
- вызывает перерендеринг

dom-tree.png
мне кажется это пример кода рядом олицетворяет, поэтому оставить как есть

hn-architecture.png
- Исходные коды
- Универсальный код приложения
- Хранилище / маршрутизатор / компоненты

- Серверная часть
- Клиентская часть

- Сборка Webpack

- Сервер Node
- Серверная сборка
- Bundle Renderer ?
- Рендеринг

- Браузер
- Клиентская сборка
- Гидратация
- HTML

mvvm.png
- Представление
- DOM

- ViewModel
- Слушатели DOM
- Привязки к данным
- Vue

- Модель
- Обычные JavaScript объекты

transition.png
- тут мне кажется можно ничего не переводить, opacity это про изменяемое свойство, остальное про используемые классы

**Comment by Alex-Sokolov** [comment]
@lex111 может ещё чего подскажешь как лучше? :)

**Comment by lex111** [comment]
> watcher

Метод-наблюдатель, по аналогии как в переводе сейчас

> data getter/setter 

Данные геттер/сеттер

> Исходные коды

Может, в единственном числе?

> Гидратация

гидрировать? (см. [пример](https://github.com/vuejs/vue-ssr-docs/blob/master/ru/README.md#%D0%A7%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BD%D1%8B%D0%B9-%D1%80%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%B8%D0%BD%D0%B3-ssr))

> Bundle Renderer ?

Оставить как есть? В том же переводе vue-ssr он написан как есть

> Обычные JavaScript объекты

Обычные JavaScript-объекты

**Comment by Alex-Sokolov** [comment]
В summary.md уже как гидратация :) а с остальным согласен

**Comment by greenroach** [comment]
![data](https://user-images.githubusercontent.com/6224866/36194496-f3017ad4-117a-11e8-91dc-07d1a0c909ed.png)

**Comment by greenroach** [comment]
![hn-architecture](https://user-images.githubusercontent.com/6224866/36245371-d39ca33c-123b-11e8-970f-f25804ad107b.png)

**Comment by greenroach** [comment]
![mvvm](https://user-images.githubusercontent.com/6224866/36247979-f1fc6208-1246-11e8-90ec-9be8a4f262c3.png)
