### ISSUE TITLE
Английские якоря в API

### ISSUE THREAD

**Issue by c01nd01r** [translation-gang/ru.vuejs.org#30]
Приветствую!
На страничке API (http://ruvuejsorg.surge.sh/v2/api/) в абзацах есть ссылки на страницы гайда с английскими якорями, тогда как у заголовков в гайде якоря русские.

Например: http://ruvuejsorg.surge.sh/v2/api/#slot 

>См. также: _Именованные слоты_

Ведет на components.html#**Named-Slots** , а должно components.html#**Именованные-слоты** 

Постараюсь в ближайшее время проверить страницу API и прислать PR.

**Comment by gbezyuk** [comment]
Спасибо что заметили!

**Comment by c01nd01r** [comment]
Меня тут немного работой привалило, но начало положено. Постараюсь поправить на выходных, но если что, вы в курсе :)
