### ISSUE TITLE
[TODO] Update docs to reflect 2.1.0 changes

### ISSUE THREAD

**Issue by Alex-Sokolov** [translation-gang/ru.vuejs.org#33]
[В секции про фильтры](http://ruvuejsorg.surge.sh/v2/guide/syntax.html#search-query-sidebar) указано, что они могут быть использованы только в выражениях в двойных фигурных скобках.

[Но с релизом Vue 2.1.0](https://gist.github.com/yyx990803/faebe22e8763f5b17572b35ed96f52fe#relaxed-filter-usage) теперь можно использовать и в `v-bind` выражениях.

Будет ли это как-то отражено в переводе документации?

**Comment by gbezyuk** [comment]
Да, мы подтянем изменения оригинальных доков.

**Comment by gbezyuk** [comment]
merge in progress
