### ISSUE TITLE
Неправильные ссылки в главе "Работа с классами и стилями"

### ISSUE THREAD

**Issue by totalamd** [translation-gang/ru.vuejs.org#335]
В оригинальном руководстве [[1]](https://vuejs.org/v2/guide/class-and-style.html) ссылки на "Object Syntax" и "Array Syntax" в главах "Binding HTML Classes" и "Binding Inline Styles" отличаются якорем в ссылке (#Object-Syntax и #Object-Syntax-1), а в русской — нет [[2]](https://ru.vuejs.org/v2/guide/class-and-style.html).

**Comment by Alex-Sokolov** [comment]
Проверил, в русской документации тоже есть (https://ru.vuejs.org/v2/guide/class-and-style.html#Использование-массивов-1)

**Comment by totalamd** [comment]
Да, но ссылки в меню ведут на якоря без номеров (в раздел Classes, а не Styles).

**Comment by Alex-Sokolov** [comment]
Да, в боковом меню ссылки без них. Надо разбираться
