### ISSUE TITLE
Неправильная ссылка в главе "Функциональные компоненты > slots() vs children"

### ISSUE THREAD

**Issue by DmitriiMers** [translation-gang/ru.vuejs.org#345]
Актуальный url: https://ru.vuejs.org/v2/guide/render-function.html#slots (меню не реагирует на click)
Рабочий url: https://ru.vuejs.org/v2/guide/render-function.html#slots-vs-children

**Comment by Alex-Sokolov** [comment]
Да, генерация ссылок там отрабатывает с ошибкой
