### ISSUE TITLE
Некорректная ссылка в API props «См. также»

### ISSUE THREAD

**Issue by HawkeyePierce89** [translation-gang/ru.vuejs.org#346]
https://ru.vuejs.org/v2/api/#props

«См. также: Входные параметры» ведёт на [Основы компонентов](https://ru.vuejs.org/v2/guide/components.html#%D0%91%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80), хотя логичнее и правильнее вести на [Входные параметры](https://ru.vuejs.org/v2/guide/components-props.html)

**Comment by Alex-Sokolov** [comment]
Спасибо! Подправил, но на другой якорь на странице. Там базовая информация о входных параметрах и в конце тоже будет ссылка на раздел с подробностями
