### ISSUE TITLE
Работа в консоли - push is not a function

### ISSUE THREAD

**Issue by danlex63** [translation-gang/ru.vuejs.org#39]
http://ru.vuejs.org/v2/guide/

В консоли, введите app4.todos.push({ text: 'Новый элемент' }). Вы увидите, что к списку добавился новый элемент.

Выдает ошибку: VM804:1 Uncaught TypeError: app4.todos.push is not a function(…)

В английской версии все в порядке.

**Comment by gbezyuk** [comment]
<img width="1440" alt="screen shot 2016-12-08 at 09 45 50" src="https://cloud.githubusercontent.com/assets/1452165/21001822/2c8e9bce-bd2b-11e6-9a3d-441b43694807.png">
что я делаю не так?

**Comment by gbezyuk** [comment]
Закрываю с резолюцией can't reproduce
