### ISSUE TITLE
Может пора обновить README.md

### ISSUE THREAD

**Issue by Alex-Sokolov** [translation-gang/ru.vuejs.org#42]
Документация с публикацией на https://ru.vuejs.org/ стала считаться официальной?)

**Comment by gbezyuk** [comment]
Согласен ) Обновим, да.

**Comment by gbezyuk** [comment]
Забавно, но это issue #42 =)

**Comment by Alex-Sokolov** [comment]
Как всё удачно сложилось :)

Может ещё и ссылки на документации Vue-router & Vuex добавить в README?

**Comment by gbezyuk** [comment]
Why not )
