### ISSUE TITLE
Сервер русской документации заблокирован Роскомнадзором

### ISSUE THREAD

**Issue by bravik** [translation-gang/ru.vuejs.org#479]
104.18.49.43 и некоторые другие айпи серверов заблокированы ковровыми блокировками Телеграма Роскомнадзором.
Недоступны ru.vuejs.org, forum.vuejs.org, chat.vuejs.org
Пожалуйста, смените сервер

**Comment by Alex-Sokolov** [comment]
ref: https://github.com/vuejs/vuejs.org/issues/2325
