### ISSUE TITLE
Joining translation-gang

### ISSUE THREAD

**Issue by ashwamegh** [translation-gang/ru.vuejs.org#481]
Hey @gbezyuk 
I would love to join **translation-gang** and I want to create **Hindi** translations repo for **VueJS** documentation translation as a primary maintainer with the people who are interested in contributing into that.

**Comment by Alex-Sokolov** [comment]
Hi! You can create repo and start translating! :) and also comment here (https://github.com/vuejs/vuejs.org/issues/2015) for looking for people who also interesting in contributing in your translation
