### ISSUE TITLE
Child - "ребенок"?

### ISSUE THREAD

**Issue by beowulfenator** [translation-gang/ru.vuejs.org#49]
Здравствуйте!

Думаете, стоит переводить "child" как "ребенок", а не как "потомок"?

**Comment by kojoru** [comment]
Ни в коем случае. Исправил.

**Comment by airyboy** [comment]
@kojoru я бы не был столь категоричным. Потомок - понятие более широкое и включает внуков и правнуков тоже :) В терминологии vue - это первый уровень иерархии, т.е. только ребенок.

**Comment by kojoru** [comment]
@airyboy нет такого термина - "класс-ребёнок", в таком контексте это никогда не используется. Если нужно подчеркнуть, что речь идёт о непосредственном потомке, можно так и написать. В этих конкретных местах всё прекрасно понятно из контекста.

**Comment by airyboy** [comment]
@kojoru родитель-потомок я тоже не встречал, в переводной литературе больше встречается предок/потомок
https://www.lingvolive.com/ru-ru/translate/en-ru/parent%2Fchild
https://www.google.ru/search?tbm=bks&hl=ru&q=%22%D0%BF%D1%80%D0%B5%D0%B4%D0%BE%D0%BA%2F%D0%BF%D0%BE%D1%82%D0%BE%D0%BC%D0%BE%D0%BA%22

**Comment by kojoru** [comment]
@airyboy главные цели такие:
1) соответствовать тому, как говорят русскоязычные программисты
2) быть понятным
3) должно звучать хорошо
4) быть достаточно точным

Не обязательно в таком порядке. Цели "быть точным переводом" принципиально не стоит, это не Шекспир и не Достоевский, к счастью. Я писал об этом [в вике](https://github.com/translation-gang/ru.vuejs.org/wiki).

**Comment by gbezyuk** [comment]
@airyboy родитель-потомок вполне встречается.

**Comment by beowulfenator** [comment]
А кто вообще отвечает за этот перевод? Можно как-то поучаствовать? Потому что я начал читать русскую версию, и до раздела "Компоненты" все прекрасно, а дальше - хоть волком вой.

**Comment by gbezyuk** [comment]
@beowulfenator глобально отвечаю я, ибо я всю эту движуху замутил и изначально всё перевёл. За стилистику и вычитку отвечает @kojoru. Принять участие элементарно — пулл-реквестами.

**Comment by kojoru** [comment]
@beowulfenator я к сожалению дотащил стилистику и вычитку туториала только до Conditional rendering (это на пару разделов раньше "Компонентов"). Вот здесь расставлены мои личные галочки: https://github.com/vuejs/vuejs.org/issues/527#issuecomment-258753396.

Рано или поздно я довычитываю до конца. Но не могу ничего пообщать по срокам.

Мы выложили так, потому что и такая документация в бесконечность раз лучше, чем никакой на русском и потому что можно в общем-то заняться этим помимо меня.

**Comment by gbezyuk** [comment]
@beowulfenator "дочерний" по мне так вполне годится. Но старший по стилю у нас, как уже было сказано, @kojoru.

**Comment by kojoru** [comment]
Да, "дочерний" — это норм, вопрос был именно к термину "класс-ребёнок"

**Comment by airyboy** [comment]
@kojoru а мне в первый раз родитель-потомок как-то резало глаз, насчет рендер, а не рендеринг в вики - я не согласен, суффикс -инг в русском языке несет в себе оттенок процесса (тренинг, маркетинг, дайвинг). Существительного _рендер_ - нет даже в английском

**Comment by beowulfenator** [comment]
Так что, можно брать и вычитывать "компоненты", а потом отправлять PR?

**Comment by kojoru** [comment]
@airyboy да, все эти места можно было бы сделать и по-другому. Но нужно принять какое-то решение и придерживаться его. Что я и сделал.

¯\_(ツ)_/¯

**Comment by kojoru** [comment]
@beowulfenator совершенно точно можно.

**Comment by gbezyuk** [comment]
@beowulfenator нужно! =)

**Comment by beowulfenator** [comment]
А есть какой-нибудь чат в гиттере?

**Comment by airyboy** [comment]
@beowulfenator вроде вот этот https://gitter.im/vuejs-ru/vuejs.org
