### ISSUE TITLE
Ошибка на странице https://ru.vuejs.org/v2/guide/list.html

### ISSUE THREAD

**Issue by armandupe** [translation-gang/ru.vuejs.org#490]
После абзаца, где речь идёт о вычисляемом свойстве в примере вместо computed указано methods. А в абзаце, где речь про методы в примере вместо methods указано computed 
![1](https://user-images.githubusercontent.com/36885141/75680719-3b261e80-5ca3-11ea-9cb8-c5c2b2b15fd1.jpg)
![2](https://user-images.githubusercontent.com/36885141/75680722-3c574b80-5ca3-11ea-8a97-ada6baa45157.jpg)

**Comment by Alex-Sokolov** [comment]
Действительно! Спасибо, поправил :)
