### ISSUE TITLE
Синхронизировать стили

### ISSUE THREAD

**Issue by Alex-Sokolov** [translation-gang/ru.vuejs.org#50]
Хотелось бы синхронизировать стили

В английской версии табличка сравнения Vue и React в фирменых цветах смотрится гораздо приятнее
https://vuejs.org/v2/guide/comparison.html

**Comment by gbezyuk** [comment]
Можете попробовать сделать PR, сравнив папки `themes`. Если не получится, чуть позже сделаю сам.

**Comment by gbezyuk** [comment]
Вроде всё ок теперь, закрываю.
