### ISSUE TITLE
Vue 3 Docs are ready for translation!

### ISSUE THREAD

**Issue by bencodezen** [translation-gang/ru.vuejs.org#505]
Hello! Just wanted to let you know that v3 docs are ready to start translating.

https://github.com/vuejs/docs-next

If you have any questions, please feel free to file an issue so we can help however we can!

**Comment by gbezyuk** [comment]
@Alex-Sokolov ;)

**Comment by Alex-Sokolov** [comment]
Amazing :) will start translating in https://github.com/translation-gang/docs-next
