### ISSUE TITLE
Issues in many times https://ru.vuejs.org/v2/guide/components-slots.html#%D0%94%D0%B5%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2-%D1%81%D0%BB%D0%BE%D1%82%D0%B0

### ISSUE THREAD

**Issue by prostoteama** [translation-gang/ru.vuejs.org#508]
<current-user v-slot="**{ user }**"> // What you destruct and why u destruct in parent but not in **slot** exectly
  {{ user.firstName }}
</current-user>

**Comment by Alex-Sokolov** [comment]
Можете чуть подробнее объяснить что не так, я не понимаю)

**Comment by Alex-Sokolov** [comment]
Пересмотрел ещё раз все вхождения `{{ user.firstName }}` на той странице. Всё как и должно быть. Если мы не так вас поняли откройте новый issue и подробнее опишите что не так
