### ISSUE TITLE
Не работают якоря на ссылках секций статьи

### ISSUE THREAD

**Issue by Alex-Sokolov** [translation-gang/ru.vuejs.org#66]
Например в Руководстве - Обработка событий, если нажать в боковой панели на "Модификаторы событий" страница не проскроллится к этой секции. Хотя вроде ID ссылки и элемента совпадают

В консоли по клику появляется ошибка:
```
TypeError: t is null[Подробнее]  smooth-scroll.min.js:2:1842
	f https://ru.vuejs.org/js/smooth-scroll.min.js:2:1842
	n.animateScroll https://ru.vuejs.org/js/smooth-scroll.min.js:2:2609
	p
```

**Comment by Alex-Sokolov** [comment]
Похоже проблема в плагине, не нравятся ему кириллические якоря... впрочем не только кириллические похоже https://github.com/cferdinandi/smooth-scroll/issues/305

**Comment by gbezyuk** [comment]
Вроде только в FF была проблема. Стала где-то ещё вылезать? Сейчас в Chrome проверил, всё вроде ок.

**Comment by Alex-Sokolov** [comment]
Ну да, в FF и не работает) видимо я пропустил issue об этом?

**Comment by gbezyuk** [comment]
Не помню, было ли issue, но точно вопрос проскакивал где-то. Я закрою, это не наша бага.

**Comment by gbezyuk** [comment]
@Alex-Sokolov — там зафиксили, можно подтянуть апдейт https://github.com/cferdinandi/smooth-scroll/issues/305 — и заодно в основной ветке тоже PR сделать, чтобы для других переводов проблема повторно не возникала.

**Comment by Alex-Sokolov** [comment]
Да, я видел) попробовал у себя на локальном обновить. Ошибок теперь в консоли нет, но скроллить на FF всё равно упорно отказывается

**Comment by Alex-Sokolov** [comment]
- Первая часть проблемы решена в #99 
- Вторая часть проблемы решится когда автор сможет https://github.com/cferdinandi/smooth-scroll/issues/310

**Comment by gbezyuk** [comment]
@Alex-Sokolov товарищ поставил wontfix и дал дельное пояснение, учтём?

**Comment by Alex-Sokolov** [comment]
Да, не было пока времени потестить с его предложением и issue в оригинальный репо сделать

**Comment by gbezyuk** [comment]
fixed with #105
