### ISSUE TITLE
Route — маршрут, path — путь, router — маршрутизатор, routing — маршрутизация

### ISSUE THREAD

**Issue by gbezyuk** [translation-gang/ru.vuejs.org#85]
subj, надо зафорсить
@kojoru ?

**Comment by kojoru** [comment]
Посмотрю чуть позднее, да

**Comment by gbezyuk** [comment]
@Alex-Sokolov вся надежда на тебя, @kojoru две недели как занят другим. Или может это тоже уже сделано и закрывать надо?

**Comment by Alex-Sokolov** [comment]
Пока не знаю, оставь может будет свободное время
