### ISSUE TITLE
Классы анимаций "-to" плохо описаны

### ISSUE THREAD

**Issue by kojoru** [translation-gang/ru.vuejs.org#86]
Класс v-enter-to и v-leave-to стоит в течение всей анимации, но нужен для указания желаемого финального состояния. Нужно это описать получше

См. https://github.com/translation-gang/ru.vuejs.org/commit/071c77ecab77fcde48c4956a51ac7dcef008b1ff#commitcomment-20407334

**Comment by gbezyuk** [comment]
В оригинальных доках тоже эта проблема есть?

**Comment by kojoru** [comment]
Я бы сказал, что да: https://vuejs.org/v2/guide/transitions.html#Transition-Classes

**Comment by Alex-Sokolov** [comment]
Подозреваю что на странице API тоже забыли добавить новые классы -to: https://vuejs.org/v2/api/#transition

**Comment by kojoru** [comment]
Nice catch!

Сможешь сделать пулл-реквест в англодоку?

**Comment by Alex-Sokolov** [comment]
Лучше переспросить, может так и задумано (https://github.com/vuejs/vuejs.org/issues/696)

**Comment by Alex-Sokolov** [comment]
#95 обратно предлагают тоже менять

**Comment by gbezyuk** [comment]
Можно закрывать?

**Comment by Alex-Sokolov** [comment]
Думаю да. Если уж расписывать подробнее — это лучше в оригинальный репо сначала внести
